#pragma warning disable CS1591
#pragma warning disable SA1600

namespace RxBim.Nuke.Generators
{
    public static class Constants
    {
        public const string Version = nameof(Version);

        public const string AppVersion = nameof(AppVersion);

        public const string VersionNumber = nameof(VersionNumber);

        public const string SetupEnv = nameof(SetupEnv);

        public const string VersionsNamespace = "RxBim.Nuke.Versions";

        public const string AutoGeneratedFileHeader = "<auto-generated/>";
    }
}