namespace RxBim.Nuke.Generators
{
    using System.Collections.Generic;
    using Microsoft.CodeAnalysis;
    using static Constants;

    /// <summary>
    /// Generates NUKE targets for different versions of CAD/BIM applications.
    /// </summary>
    [Generator]
    public class VersionsTargetsGenerator : ISourceGenerator
    {
        private GeneratorExecutionContext _context;

        /// <inheritdoc />
        public void Initialize(GeneratorInitializationContext context)
        {
// #if DEBUG
//             Debugger.Launch();
// #endif
        }

        /// <inheritdoc />
        public void Execute(GeneratorExecutionContext context)
        {
            _context = context;
            var appVersion = _context.Compilation.GetTypeByMetadataName(AppVersionClassTypeName);
            if (appVersion is null)
                return;
            var versionNumbers = GetVersionNumbers();
            foreach (var versionNumber in versionNumbers)
            {
                var source = GetSource(versionNumber);
                _context.AddSource($"IVersionBuild{versionNumber}.g.cs", source);
            }
        }

        private static string GetSource(string versionNumber)
        {
            var source = $@"// <auto-generated/>
#pragma warning disable CS1591
#pragma warning disable SA1205
#pragma warning disable SA1600

namespace RxBim.Nuke.Versions
{{
    using global::Nuke.Common;

    partial interface IVersionBuild
    {{
        Target SetupEnv{versionNumber} => _ => _           
            .Executes(() => this.SetupEnvironment(""{versionNumber}""));

        Target Compile{versionNumber} => _ => _.DependsOn(SetupEnv{versionNumber}).Triggers(Compile);

        Target Restore{versionNumber} => _ => _.DependsOn(SetupEnv{versionNumber}).Triggers(Restore);

        Target Pack{versionNumber} => _ => _.DependsOn(SetupEnv{versionNumber}).Triggers(Pack);

        Target Release{versionNumber} => _ => _.DependsOn(SetupEnv{versionNumber}).Triggers(Release);

        Target Prerelease{versionNumber} => _ => _.DependsOn(SetupEnv{versionNumber}).Triggers(Prerelease);

        Target Publish{versionNumber} => _ => _.DependsOn(SetupEnv{versionNumber}).Triggers(Publish);
    }}
}}";
            return source;
        }

        private static IEnumerable<string> GetVersionNumbers()
        {
            return new[]
            {
                "2019",
                "2020",
                "2021",
                "2022",
                "2023"
            };
        }
    }
}