namespace RxBim.Nuke.Generators
{
    /// <summary>
    /// Utilities for properties source.
    /// </summary>
    internal static class PropsSourceUtils
    {
        /// <summary>
        /// Returns properties for versions source.
        /// </summary>
        public static string GetVersionPropertiesSource()
        {
            return @"// <auto-generated>
using Nuke.Common;
using RxBim.Nuke.Versions;

/// <summary>
/// Build class.
/// </summary>
partial class Build : IVersionBuild
{
    /// <inheritdoc />
    [Parameter]
    public AppVersion AppVersion { get; set; }

    /// <inheritdoc />
    [Parameter]
    public AppVersionNumber AppVersionNumber { get; set; }
}";
        }
    }
}