namespace RxBim.Nuke.Generators
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.CodeAnalysis;
    using static Constants;

    /// <summary>
    /// Generates RxBim.Nuke.Versions sources.
    /// </summary>
    [Generator]
    public class VersionsSourcesGenerator : ISourceGenerator
    {
        /// <inheritdoc />
        public void Initialize(GeneratorInitializationContext context)
        {
        }

        /// <inheritdoc />
        public void Execute(GeneratorExecutionContext context)
        {
            if (!context.TryGetVersionNumbersFromContextAssembly(out var versionNumbers))
                return;

            var verNumSource = GetVersionNumbersSource(versionNumbers);
            context.AddSource($"{VersionNumber}.g.cs", verNumSource);
        }

        private static string GetVersionNumbersSource(IEnumerable<string> versionNumbers)
        {
            var values = string.Join(
                Environment.NewLine,
                versionNumbers.Select(x =>
                    $"        public static {VersionNumber} {Constants.Version}{x} = new() {{ Value = \"{x}\" }};"));

            return $$"""
                // {{AutoGeneratedFileHeader}}
                #pragma warning disable CS1591, SA1401, SA1600, SA1601, CA2211
                
                namespace {{VersionsNamespace}}
                
                {
                    public partial class {{VersionNumber}}
                    {
                {{values}}
                    }
                }
                """;
        }
    }
}