<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDependencyFile>true</GenerateDependencyFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dependency\RxBim.Shared.Tests.Dependency.csproj" />
  </ItemGroup>
</Project>