namespace RxBim.Nuke.Generators
{
    using static Constants;

    /// <summary>
    /// Utilities for properties source.
    /// </summary>
    internal static class PropertiesSourceUtils
    {
        /// <summary>
        /// Returns properties for versions source.
        /// </summary>
        public static string GetVersionPropertiesSource()
        {
            return $@"// {AutoGeneratedFileHeader}
using Nuke.Common;
using {VersionsNamespace};

/// <summary>
/// Build class.
/// </summary>
partial class Build : IVersionBuild
{{
    /// <inheritdoc />
    [Parameter]
    public {AppVersion} {AppVersion} {{ get; set; }}

    /// <inheritdoc />
    [Parameter]
    public {VersionNumber} {VersionNumber} {{ get; set; }}
}}";
        }
    }
}