namespace RxBim.Nuke.Generators
{
    using static Constants;

    /// <summary>
    /// Utilities for properties source.
    /// </summary>
    internal static class PropertiesSourceUtils
    {
        /// <summary>
        /// Returns properties for versions source.
        /// </summary>
        public static string GetVersionPropertiesSource()
        {
            return $$"""
                // {{AutoGeneratedFileHeader}}
                using Nuke.Common;
                using {{VersionsNamespace}};
                
                /// <summary>
                /// Build class.
                /// </summary>
                partial class Build : IVersionBuild
                {
                    /// <inheritdoc />
                    [Parameter("Version for one type of CAD application: 'Autocad2023', 'Revit2022' etc.")]
                    public {{AppVersion}} {{AppVersion}} { get; set; }
                
                    /// <inheritdoc />
                    [Parameter("Version number for all types of CAD applications: '2022', '2023' etc.")]
                    public {{VersionNumber}} {{VersionNumber}} { get; set; }
                }
                """;
        }
    }
}